### ISSUE TITLE
LTS table issues

### ISSUE THREAD

**Issue by webimpress** [zendframework/zf3-web#109]
I was looking on LTS table and I have found there some confusions:

![image](https://user-images.githubusercontent.com/7423207/50053491-02e20100-012e-11e9-8db2-25dc2a21432c.png)

![image](https://user-images.githubusercontent.com/7423207/50053502-37ee5380-012e-11e9-8349-19b373165f1e.png)

(the same versions and different end dates)

https://framework.zend.com/long-term-support

**Comment by weierophinney** [comment]
In the case of zend-component-installer, there's no problem - the two entries for 1.0 are both relevant due to the different contexts (ZendSkeletonApplication vs zend-expressive-skeleton).

However, that first one, for zend-stdlib, **is** problematic, so I'll take a look and see if I can find a solution.
